#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Mar 25 14:47:22 IST 2026
maven-metadata-aspose.xml.error=
maven-metadata-aspose.xml.lastUpdated=1774430242871
maven-metadata-atlassian-proxy.xml.lastUpdated=1774430114276
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1774430242873
maven-metadata-clojars.xml.error=
maven-metadata-clojars.xml.lastUpdated=1774430242871
maven-metadata-gradle-plugins.xml.error=
maven-metadata-gradle-plugins.xml.lastUpdated=1774430242871
maven-metadata-jenkins-releases.xml.error=
maven-metadata-jenkins-releases.xml.lastUpdated=1774430242872
maven-metadata-maven-central.xml.error=
maven-metadata-maven-central.xml.lastUpdated=1774430242870
maven-metadata-mulesoft-public.xml.lastUpdated=1774430114281
maven-metadata-mulesoft-releases.xml.error=
maven-metadata-mulesoft-releases.xml.lastUpdated=1774430242872
maven-metadata-mulesoft.xml.error=
maven-metadata-mulesoft.xml.lastUpdated=1774430242871
maven-metadata-sonatype\ forge.xml.error=
maven-metadata-sonatype\ forge.xml.lastUpdated=1774430242872
maven-metadata-terracotta.xml.error=
maven-metadata-terracotta.xml.lastUpdated=1774430242870
maven-metadata-typesafe.xml.error=
maven-metadata-typesafe.xml.lastUpdated=1774430242872
